name: Pull-request workflow
on:
  pull_request:
    branches:
      - main
jobs:
  tests-unitaires:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du repo
        uses: actions/checkout@v2
      - name: Récupération de java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Execution des tests
        run: mvn test
  build-app:
    needs: tests-unitaires
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du repo
        uses: actions/checkout@v2
      - name: Récupération de java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Création du jar
        run: mvn package
      - name: Upload du jar
        uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: ./target/testDemo-0.0.1-SNAPSHOT.jar
  docker:
    nedds: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du repo
        uses: actions/checkout@v2
      - name: Récupération du jar
        uses: actions/download-artifact@v2
        with:
          name: app.jar
      - name: Instal QEMU Docker
        uses: docker/setup-qemu-action@v1
      - name: Instal BuildX docker
        uses: docker/setup-buildx-action@v1
      - name: Connection a Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build et push mon image docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ropi59/testdemo:latest
